- name: Mac Playbook
  hosts: localhost
  connection: local
  become: false
  vars:
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false
      
  pre_tasks:
    - name: Run Pre-check
      import_tasks: 'tasks/common.yml'
        
  tasks:
    - name: Homebrew
      import_tasks: 'tasks/homebrew.yml'
      when: ansible_facts['os_family'] == "Darwin"
 
    - name: Rust
      import_tasks: 'tasks/rust.yml'

    - name: Git
      import_tasks: 'tasks/git.yml'
          
    - name: Golang
      import_tasks: 'tasks/golang.yml'
        
    - name: Neovim
      import_tasks: 'tasks/neovim.yml'
        
    - name: Dotfiles
      import_tasks: 'tasks/dotfiles.yml'
