- name: Install software
  hosts: localhost
  connection: local
  become: false
  vars:
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false
      
  pre_tasks:
    - name: Read Inputs
      include_vars:
        file: inputs.yml
        name: data
      tags:
        - always
        
    - name: Homebrew | Check Installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check
      tags: 
        - homebrew 

    - name: Homebrew | Fail
      fail:
        msg: Homebrew is missing, install from http://brew.sh
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing
      tags: 
        - homebrew 

    - name: Homebrew | Install
      shell: /usr/bin/ruby -e "$ -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing
      tags: 
         - homebrew 

    - name: Rust | Check Installed
      stat: 
        path: $HOME/.cargo/bin/cargo
      register: cargo_exists
      ignore_errors: true
      tags:
        - rust
          
    - name: Golang | Check Installed
      stat: 
        path: /usr/local/go
      register: golang_exists
      ignore_errors: true
      tags:
        - golang
    
    - name: Golang | Get Installed Version 
      command: /usr/local/go/bin/go version 
      register: golang_current_version
      when: golang_exists.stat.exists
      changed_when: false 
      tags:
        golang
        
    - name: Golang | Check Latest Version 
      uri:
        url: https://go.dev/VERSION?m=text
        return_content: yes
      register: golang_latest_version
      changed_when: false 
      tags:
        - golang

    - name: Golang | Set Latest Version
      set_fact: golang_latest_version="{{ golang_latest_version.content[2:] }}"
      tags:
        - golang
          
    - name: Neovim | Check Installed
      stat: 
        path: /usr/local/nvim/bin/nvim
      register: nvim_exists
      ignore_errors: true
      tags:
        - nvim
          
    - name: Neovim | Create Install Directory
      become: true
      file:
        path: /usr/local/nvim 
        state: directory
      when: not nvim_exists.stat.exists
      tags:
        - nvim

  tasks:
    - name: Homebrew | Update
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists
      tags:
        - homebrew
    
    - name: Homebrew | Install Casks
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop: "{{data.brew_casks}}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
      tags:
        - homebrew
        
    - name: Homebrew | Install Formulas
      homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{data.brew_formulas}}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists
      tags:
        - homebrew

    - name: Rust | Install
      shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
      when: 
        - not cargo_exists.stat.exists
      tags:
        - rust

    - name: Rust | Update
      shell: rustup update 
      tags:
        - update
        - rust

    - name: Rust | Cargo Install
      community.general.cargo:
        name: "{{item}}"
        state: present
      loop: "{{data.cargo_binaries}}"
      register: result
      until: result is successful
      tags:
        - rust

          
    - name: Git | Clone Repos
      git:
        repo: "{{item.repo}}"
        dest: "{{item.dest}}"
        clone: yes
        update: no
      loop: "{{data.git_repos}}"
      tags:
        - git
          
    - name: Golang | Install
      become: true
      unarchive:
        src: "https://go.dev/dl/go{{ golang_latest_version }}.{{ ansible_os_family|lower }}-{{ ansible_architecture }}.tar.gz"
        dest: /usr/local
        mode: 0755
        remote_src: yes
        creates: /usr/local/go
      when: not golang_exists.stat.exists
      tags:
        - golang
          
    - name: Golang | Update
      become: true
      unarchive:
        src: "https://go.dev/dl/go{{ golang_latest_version }}.{{ ansible_os_family|lower }}-{{ ansible_architecture }}.tar.gz"
        dest: /usr/local
        mode: 0755
        remote_src: yes
        creates: /usr/local/go
      when: golang_exists.stat.exists and golang_current_version != golang_latest_version
      tags:
        - update
        - golang

    - name: Neovim | Install
      become: true
      unarchive:
        src: https://github.com/neovim/neovim/releases/latest/download/nvim-macos.tar.gz
        dest: /usr/local/nvim 
        mode: 0755 
        remote_src: yes 
        creates: /usr/local/nvim/bin/nvim 
        extra_opts: 
          - --strip-components=1
      when: not nvim_exists.stat.exists
      tags:
        - nvim
          
    # - name: Neovim | Update
    #   become: true
    #   unarchive:
    #     src: https://github.com/neovim/neovim/releases/latest/download/nvim-macos.targ.gz
    #     dest: /usr/local/nvim 
    #     mode: 0755 
    #     remote_src: yes 
    #     creates: /usr/local/nvim/bin/nvim 
    #     extra_opts: 
    #       - --strip-components=1
    #   when: not nvim_exists.stat.exists
    #   tags:
    #     - update
    #     - nvim
