- name: Install software
  hosts: localhost
  connection: local
  become: false
  vars:
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false
      
  pre_tasks:
    - name: Read Inputs
      include_vars:
        file: tasks/inputs.yml
        name: data
      tags:
        - always
        
    - name: Run Pre-check
      import_tasks: 'tasks/common.yml'
        
  tasks:
    - name: Homebrew
      import_tasks: 'tasks/homebrew/main.yml'
 
    - name: Rust
      import_tasks: 'tasks/rust/main.yml'

    - name: Git
      import_tasks: 'tasks/git/main.yml'
          
    - name: Golang
      import_tasks: 'tasks/golang/main.yml'
        
    - name: Neovim
      import_tasks: 'tasks/neovim/main.yml'
