- name: Git | Setup email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_email }}"
  tags:
  - git
  - git-config
    
- name: Git | Setup name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_name }}"
  tags:
  - git
  - git-config
    
- name: Git | Clone Repos
  git:
    repo: "{{item.repo}}"
    dest: "{{item.dest}}"
    clone: yes
    update: no
  loop: "{{ git_repos }}"
  tags:
    - git
