- name: Homebrew | Update
  homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists
  tags:
    - homebrew
      
- name: Homebrew | Install Taps
  homebrew_tap:
    name: "{{ item }}"
  loop: "{{ brew_taps }}"
  tags:
    - homebrew 
    - taps
    - casks
      
- name: Homebrew | Install Casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_casks }}"
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
  tags:
    - homebrew
    - casks
    
- name: Homebrew | Install Formulas
  homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_formulas }}"
  register: result
  until: result is successful
  when: homebrew_check.stat.exists
  tags:
    - homebrew
    - formulas
